#!/bin/bash
# Part of Docker Devour project

echo "#!/bin/python -tt"
echo
echo "'''"
echo " Docker Devour Python Flag bindings"
echo " Autogenerated by $0 against:"
echo " `docker -v 2>&1` "
echo " May require manual edits afterwards!"
echo "'''"
echo

VERB_HEADER='%s_FLAGS=[\n'
FLAG_FORMAT='	Flag.new(names=[%s], type=%s, default=%s),'
VERB_FOOTER=']'

printf "$FILE_HEADER" "`docker -v 2>&1`" "$0"

for VERB in `./extract-verbs.sh`; 
do
	printf "$VERB_HEADER" "`echo $VERB | awk '{print toupper($0)}'`"
	set -f
	IFS='
	'
	for FLAG in `./extract-flags.sh $VERB | sed -e 's/^--\([a-z\-]*\)=.*/"\1"/i' -e 's/^-\([a-z]*\)/"\1", /i' -e 's/,\+ --\([a-z\-]*\)=.*/"\1"/i'`; 
	do
		printf "$FLAG_FORMAT\n" $FLAG 'FlagType.Invalid' 'True'
	done
	echo $VERB_FOOTER ; echo ; echo
done
